<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payload Simulation</title>
    <script type="text/javascript">
        function sendMessage() {
            fetch('http://10.0.2.15:8080', {  // Updated with your actual server IP address
                method: 'POST',
                headers: {
                    'Content-Type': 'text/plain',
                },
                body: 'This is a simulated message from the dummy number.'
            })
            .then(response => response.text())
            .then(data => console.log('Message sent:', data))
            .catch(error => console.error('Error:', error));
        }

        window.onload = sendMessage;
    </script>
</head>
<body>
    <h1>Simulated Payload</h1>
    <p>If you see this message, the payload has been executed and a simulated message was sent.</p>
</body>
</html>
